"use client";
import Head from "next/head";
import Image from "next/image";
import style from "../styles/Home.module.css";
import Hero from "@/components/hero/hero";
import ShopCards from "@/components/shopCards/shopCards";

import laptop from "../public/images/laptop-bg.png";
import Card from "./../components/card/card";
import Corousel from "@/components/slider/corousel";

import OnlineIcon from "@/public/svgs/Online";
import GiftIcon from "@/public/svgs/Gift";
import MoneyIcon from "@/public/svgs/Money";
import GlobeIcon from "@/public/svgs/Globe";

import bg1 from "../public/images/bg1.jpg";
import bg2 from "../public/images/bg2.jpg";
import bg3 from "../public/images/bg3.jpg";
import bg4 from "../public/images/bg4.jpg";

import { useEffect } from "react";

//  AOS Library
import Aos from "aos";
import "aos/dist/aos.css";

const cards = [
  {
    text: "GameStop to Offer Up to $1 Billion in",
    image: bg1,
  },
  {
    text: "SPAC Called 5G Edge Wants to Go Public",
    image: bg2,
  },
  {
    text: "Yoga Event Helping marginalised Women",
    image: bg3,
  },
  {
    text: "Dual-Drive Storage for Workflows",
    image: bg4,
  },
];

const onlinePayments = [
  {
    icon: <GlobeIcon />,
    title: "Free Delivery",
    text: "Free shipping on all order",
  },
  {
    icon: <OnlineIcon />,
    title: "Online support 24/7",
    text: "Support online 24 hours a day",
  },
  {
    icon: <MoneyIcon />,
    title: "Money return",
    text: "Back guarantee under 7 days",
  },
  {
    icon: <GiftIcon />,
    title: "Member Discount",
    text: "Onevery order over $120.00",
  },
];

export default function Home() {
  // AOS LIBRARY REACT JS
  useEffect(() => {
    Aos.init({ duration: 1000 });
  }, []);

  return (
    <>
      <Head>
        <title>Digital Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <ShopCards />
        {/*  Laptop -bg  */}
        <div className={`${style["laptop-container"]}`} data-aos="fade-up">
          <div
            className={`${style["laptop-bg-overlay"]}`}
            data-aos="fade-up"
          ></div>
          <div className={style.content}>
            <div className={style.text}>
              <h5>Asus Zenbook Duo</h5>
              <h2>
                The Laptop <br />
                Of Tomorrow
              </h2>

              <button>Shop Pre Order </button>
            </div>
            <div className={style.image}>
              <Image src={laptop} alt="laptop" fill />
            </div>
          </div>
        </div>
        {/* Slider */}
        <Corousel />
        {/*    Two Cards */}
        <div className={` ${style.accessories} `}>
          <div
            className={`${style.card} ${style["card-1"]}`}
            data-aos="fade-up"
          >
            <div className={style["camera-overlay"]} />
            <h5> camera Accessories</h5>
            <h2>
              Launch Party <br /> Nice Photos
            </h2>
            <button className={`${style.btn} ${style["btn-1"]}`}>
              Shop By Category
            </button>
          </div>
          <div
            className={`${style.card} ${style["card-2"]}`}
            data-aos="fade-up"
          >
            <div className={style["videogame-overlay"]} />
            <h5> game Accessories</h5>
            <h2>
              Enjoy Game <br /> High Tech
            </h2>
            <button className={`${style.btn} ${style["btn-2"]}`}>
              Shop By Category
            </button>
          </div>
        </div>

        {/*     Cards */}
        <div className={`${style.container} ${style["card-container"]}`}>
          <h3>Latest Posts</h3>

          <div className={style["grid-container"]} data-aos="fade-up">
            {cards.map((card, index) => (
              <Card key={index} text={card.text} image={card.image} />
            ))}
          </div>
        </div>
        {/* Online Payments  */}
        <div className={`${style["payment-container"]}`}>
          <div className={style["grid-container"]}>
            {onlinePayments.map((card, index) => (
              <div
                className={style["card-payment"]}
                key={index}
                data-aos="fade-up"
              >
                <div className={style.icon}>{card.icon}</div>
                <div className={style.paymentcontent}>
                  <h5>{card.title}</h5>
                  <p>{card.text}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
